# Generated by Django 4.1.3 on 2022-12-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('subtitle', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
